.TH CRUFT-NG 8
.SH NAME
cruft-ng \- Check the filesystem for cruft (missing and unexplained files)
.SH SYNOPSIS
.B cruft-ng
.\".I "[-h] [-d DRIVES] [--chroots CHROOTS] [--ignore IGNORES] [-r REPORTFILE] [-m ADDRESS]"
.SH "DESCRIPTION"
.\"This manual page documents briefly the
.\".BR cruft 
.\"command.
.\"Please see /usr/share/doc/cruft/README.gz for more information.
.\".PP
.B cruft-ng
is a program that goes over the Debian packaging system's database, and
compares the contents of that with the files actually on your system, and
produces a summary of the differences.
.SH OPTIONS
There is currently no option recognized.
.\"The following options are recognized:
.\".TP
.\".B \-h
.\"Show a summary of options and exit.
.\".TP
.\".B \-d \fIDRIVES
.\"Search only the listed filesystems.
.\".I DRIVES
.\"should be an absolute path, or a quoted, space-separated list of multiple
.\"absolute paths (eg, "/ /usr /home"). Multiple \-d options are allowed as well. If not specified,
.\".BR cruft
.\"attempts to autodetect which filesystems to scan.
.\".TP
.\".B \-\-chroots \fICHROOTS
.\"Do not perform validity checks on symlinks under these directories. Useful for
.\"whatever chroots are set up in the system.
.\".TP
.\".B \-\-ignore \fIIGNORES
.\"Treat the directory trees in
.\".I IGNORES
.\"as if they did not exist.
.\".I IGNORES
.\"should be an absolute path, or a quoted, space-separated list of multiple
.\"absolute paths. Multiple \-\-ignore options are allowed as well.
.\".TP
.\".B \-r \fIREPORTFILE
.\"Output report to 
.\".I REPORTFILE
.\"instead of standard output.
.\".TP
.\".B \-m \fIADDRESS
.\"Mail report to 
.\".I ADDRESS.
.\".TP
.\".SH "ENVIRONMENT VARIABLES"
.\"It is possible to get some debugging information from cruft by setting the variable
.\".B CRUFT_DEBUG
.\"to 1. If you need more detailed information on what cruft is doing, set it to 2.
.SH "SEE ALSO"
Documentation from original cruft package:
/usr/share/doc/cruft/README.gz
.SH AUTHOR
This manual page was written by Alexandre Detiste <alexandre@detiste.be>,
for the Debian GNU/Linux system (but may be used by others).
