#!/bin/sh

set -e

test -z "$CRUFT_ROOT" || exit 1

ALTDIR="/etc/alternatives"

update-alternatives --get-selections | while read -r alternative _y _z
do
    echo "$ALTDIR/$alternative"
    update-alternatives --query "$alternative" 2>/dev/null | while read -r line
    do
        case "$line" in
            Name:*)
                ;;
            Link:*)
                echo "${line#* }"
                ;;
            Slaves:*)
                ;;
            Status:*)
                break
                ;;
            *)
                alt="$ALTDIR/${line% *}"
                test -e "$alt" && echo "$alt"

                link="${line#* }"
                test -e "$link" && echo "$link"
                ;;
        esac
    done
done

exit 0
