#!/bin/sh
set -e

test -z "$CRUFT_ROOT" || exit 1

ALTDIR="/etc/alternatives"

update-alternatives --get-selections | while read -r alternative _y _z
do
    update-alternatives --query "$alternative" 2>/dev/null | while read -r line
    do
        case "$line" in
            Name:*|Slaves:*|Status:*|Best:*)
                ;;
            Link:*)
                link="${line#* }"
                ;;
            Value:*)
                test -e "${line#* }" && printf "%s\n%s\n" "$ALTDIR/$alternative" "$link" || true
                ;;
            '')
                break
                ;;
            *)
                alt="$ALTDIR/${line% *}"
                test -e "$alt" && echo "$alt" || true

                target="${line#* }"
                test -e "$target" && echo "$target" || true
                ;;
        esac
    done
done

exit 0
