#! /bin/sh
set -e

echo 'this run all explain scripts'
for script in /usr/libexec/cruft/*
do
    echo $script
    $script > /dev/null
done

echo 'standard run'
cruft

echo '--locate'
cruft --locate

echo 'should print: "base-passwd"'
cruft /etc/passwd | grep base-passwd

echo 'this prints the environment:'
env | sort
