#!/bin/sh
set -e

test -d "$CRUFT_ROOT/etc/apparmor.d" || exit 0

test -d "$CRUFT_ROOT/etc/apparmor.d/local" && echo /etc/apparmor.d/local

find "$CRUFT_ROOT/etc/apparmor.d/" -maxdepth 1 -type f -printf "%f\n" | while read -r file
do
	if [ -e "$CRUFT_ROOT/etc/apparmor.d/cache/$file" ]; then echo "/etc/apparmor.d/cache/$file"; fi
	if [ -e "$CRUFT_ROOT/etc/apparmor.d/disable/$file" ]; then echo "/etc/apparmor.d/disable/$file"; fi
	if [ -e "$CRUFT_ROOT/etc/apparmor.d/local/$file" ]; then echo "/etc/apparmor.d/local/$file"; fi
done


test -d "$CRUFT_ROOT/etc/apparmor.d/abstractions" || exit 0

test -d "$CRUFT_ROOT/etc/apparmor.d/local/abstractions" && echo /etc/apparmor.d/local/abstractions

find "$CRUFT_ROOT/etc/apparmor.d/abstractions" -maxdepth 1 -type f -printf "%f\n" |
while read -r file
do
	if [ -e "$CRUFT_ROOT/etc/apparmor.d/local/abstractions/$file" ]; then echo "/etc/apparmor.d/local/abstractions/$file"; fi
done

exit 0
