#!/bin/sh
set -e

[ -d "$CRUFT_ROOT/etc/ssl/certs" ] || exit 0

find "$CRUFT_ROOT/etc/ssl/certs" -type l -name \*.pem |
 while read -r name
 do
   [ -e "$name" ] && echo "${name#"$CRUFT_ROOT"}"
 done

find "$CRUFT_ROOT/etc/ssl/certs" -type l -name '????????.?' |
 while read -r name
 do
   [ -e "$name" ] && echo "${name#"$CRUFT_ROOT"}"
 done

find "$CRUFT_ROOT/etc/ssl/certs" -type l -name '????????' |
 while read -r name
 do
	link=$(readlink "$name")
   [ "$link" = "ssl-cert-snakeoil.pem" ] && echo "${name#"$CRUFT_ROOT"}"
 done
