#!/bin/sh
set -e

dpkg-query -L grub-pc-bin 2>/dev/null | grep ^/usr/lib/grub | grep -e '\.mod' -e '\.lst' -e '\.o'| sed 's#usr/lib#boot#'
dpkg-query -L grub-pc-bin 2>/dev/null | grep ^/usr/lib/grub | grep -e '\.img' | sed 's#usr/lib#boot#'  | while read -r o; do if [ -e "$o" ]; then echo "$o"; fi; done
