#!/bin/sh
set -e

d=/boot/grub
if [ ! -d "$d" ]; then d=/boot/boot/grub; fi
if [ ! -d "$d" ]; then exit 1; fi
if [ "$d" = "/boot/boot/grub" ]
then
    echo /boot/boot
fi
echo $d
find $d -type f -name stage1 -or -name stage2 -or -name \*_stage1_5 -or -name device.map -or -name menu.lst\* -or -name default
