#!/bin/sh
set -ex

test -z "$CRUFT_ROOT" || exit 0

dpkg-query -L grub-efi-amd64-bin 2>/dev/null | grep ^/usr/lib/grub/x86_64-efi | grep -e '\.mod$' -e '\.lst$' | sed 's#usr/lib#boot#'

test -x /boot/efi || exit 0

find /boot/efi \
     -iwholename '/boot/efi/efi/*/bootx64.csv' \
  -o -iwholename '/boot/efi/efi/*/bootx64.efi' \
  -o -iwholename '/boot/efi/efi/*/fbx64.efi' \
  -o -iwholename '/boot/efi/efi/*/fw' \
  -o -iwholename '/boot/efi/efi/*/fw/*' \
  -o -iwholename '/boot/efi/efi/*/fwupdx64.efi' \
  -o -iwholename '/boot/efi/efi/*/grub.cfg' \
  -o -iwholename '/boot/efi/efi/*/grubx64.efi' \
  -o -iwholename '/boot/efi/efi/*/mmx64.efi' \
  -o -iwholename '/boot/efi/efi/*/shimx64.efi' \
