#!/bin/sh
set -e

test -d "$CRUFT_ROOT/usr/share/icons/" || exit 0

find "$CRUFT_ROOT/usr/share/icons/" -wholename "$CRUFT_ROOT/usr/share/icons/*/icon-theme.cache" | sed "s#^$CRUFT_ROOT##" | while read -r cache
do
	echo "@$cache" | sed -e 's#/icon-theme.cache##'
	echo "$cache"
done
