#!/bin/sh
set -e

packages1="$(dpkg-query -W -f='${db:Status-Abbrev}-${binary:Package}\n' '*-icon-theme' 2> /dev/null | grep ^i | cut -f 2 -d \- )"
packages2="$(dpkg-query -W -f='${db:Status-Abbrev}-${binary:Package}\n' 'kde-icons-*'  2> /dev/null | grep ^i | cut -f 4 -d \- )"
packages="$(echo $packages1 $packages2 | sort -u)"

# headless setups won't have any icons
[ -z "$packages" ] && exit 0

for package in $packages
do
	# lxde-icon-theme
	if [ "$package" = "lxde" ]
	then
		package=nuoveXT2
	fi

	if [ "$package" = "numix" ]
	then
		find /usr/share/icons/ -iwholename /usr/share/icons/Numix-Light/icon-theme.cache
	fi

	if [ "$package" = "humanity" ]
	then
		find /usr/share/icons/ -iwholename /usr/share/icons/Humanity-Dark/icon-theme.cache
	fi

	find /usr/share/icons/ -iwholename /usr/share/icons/$package/icon-theme.cache
done
