#!/bin/sh

set -e

test -z "$CRUFT_ROOT" || exit 0

test -d /boot/grub/themes/kali || exit 0
echo /boot/grub/themes
echo /boot/grub/themes/kali

find /usr/share/grub/themes/kali/ -maxdepth 1 -type f -printf "%f\n" | while read -r t
do
    test -f "/boot/grub/themes/kali/$t" && echo "/boot/grub/themes/kali/$t"
done
