#!/bin/sh

set -e

test -z "$CRUFT_ROOT" || exit 0

test -d /usr/share/kali-menu/applications/ || exit 0

find /usr/share/kali-menu/applications/ -maxdepth 1 -type f -printf "%f\n" | while read -r m
do
    test -f "/usr/share/applications/$m" && echo "/usr/share/applications/$m"
done
