#!/bin/sh

set -e

test -d /usr/share/kali-menu/applications/ || exit 0

cd /usr/share/kali-menu/applications/

for m in *
do
    test -f /usr/share/applications/$m && echo /usr/share/applications/$m
done
