#!/bin/sh
set -e

[ -e /initrd.img ] && echo /initrd.img
[ -e /initrd.img.old ] && echo /initrd.img.old
[ -e /vmlinuz ] && echo /vmlinuz
[ -e /vmlinuz.old ] && echo /vmlinuz.old
[ -e /etc/apt/apt.conf.d/01autoremove-kernels ] && echo /etc/apt/apt.conf.d/01autoremove-kernels

packages="$(dpkg-query -W -f='${binary:Package}\n' 'linux-image-*-*' 2> /dev/null)"
# RaspberryPi uses a custom kernel, so there is no linux-image-*
[ -z "$packages" ] && exit 0

for package in $packages
do
	echo $package
	ver=$(echo $package | awk '{ print substr($1,13,20); }' )
	[ -e "/boot/initrd.img-${ver}"                 ] && echo /boot/initrd.img-${ver}
        [ -e "/lib/modules/${ver}/modules.alias"       ] && echo /lib/modules/${ver}/modules.alias
        [ -e "/lib/modules/${ver}/modules.alias.bin"   ] && echo /lib/modules/${ver}/modules.alias.bin
        [ -e "/lib/modules/${ver}/modules.builtin.bin" ] && echo /lib/modules/${ver}/modules.builtin.alias.bin
        [ -e "/lib/modules/${ver}/modules.builtin.bin" ] && echo /lib/modules/${ver}/modules.builtin.bin
        [ -e "/lib/modules/${ver}/modules.dep"         ] && echo /lib/modules/${ver}/modules.dep
        [ -e "/lib/modules/${ver}/modules.dep.bin"     ] && echo /lib/modules/${ver}/modules.dep.bin
        [ -e "/lib/modules/${ver}/modules.devname"     ] && echo /lib/modules/${ver}/modules.devname
        [ -e "/lib/modules/${ver}/modules.softdep"     ] && echo /lib/modules/${ver}/modules.softdep
        [ -e "/lib/modules/${ver}/modules.symbols"     ] && echo /lib/modules/${ver}/modules.symbols
        [ -e "/lib/modules/${ver}/modules.symbols.bin" ] && echo /lib/modules/${ver}/modules.symbols.bin
	[ -e "/var/lib/initramfs-tools/${ver}"         ] && echo /var/lib/initramfs-tools/${ver}
done
