#!/bin/sh
set -e

test -d /usr/share/munin/plugins || exit 0

find /usr/share/munin/plugins -maxdepth 1 -type f -printf "%f\n" | while read -r file
do
	if [ -e "/etc/munin/plugins/$file" ]
	then
		echo "/etc/munin/plugins/$file"
	fi
done
