#!/bin/sh

set -e

test -z "$CRUFT_ROOT" || exit 0

test -d /etc/sv || exit 0

find /etc/sv/ -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | while read -r package
do
    link="/etc/runit/runsvdir/default/${package}"
    test -e "$link" && echo "$link"
done

exit 0
