#!/bin/sh
set -e

for user in root $(awk -F: '{ if ( 1000 <= $3 && $3 < 30000 ) print $1 }' /etc/passwd)
do
	home=$(grep "^$user:" /etc/passwd | cut -d: -f6)

	[ -e "/var/lib/sudo/$user" ] && find "/var/lib/sudo/$user" 2>/dev/null || true
	[ -e "/var/lib/sudo/lectured/$user" ] && echo "/var/lib/sudo/lectured/$user"
	[ -e "/var/lib/sudo/ts/$user" ] && echo "/var/lib/sudo/ts/$user"
done
exit 0
