#!/bin/sh
set -e

test -z "$CRUFT_ROOT" || exit 0

for user in root $(awk -F: '{ if ( 1000 <= $3 && $3 < 30000 ) print $1 }' /etc/passwd)
do
	if test -e "/var/lib/sudo/$user"
	then
		find "/var/lib/sudo/$user" 2>/dev/null || true
	fi
	[ -e "/var/lib/sudo/lectured/$user" ] && echo "/var/lib/sudo/lectured/$user"
	[ -e "/var/lib/sudo/ts/$user" ] && echo "/var/lib/sudo/ts/$user"
done
exit 0
