#!/bin/sh
set -e

test -x /usr/sbin/dkms || exit 0

/usr/sbin/dkms status -m virtualbox | while read -r _x ver arch _y
do
    ver=$(echo "$ver" | tr -d ' ,')
    echo "/lib/modules/${ver}/updates"
    echo "/lib/modules/${ver}/updates/dkms"
    for mod in vboxdrv vboxnetadp vboxnetflt vboxpci
    do
        for ext in ko ko.xz
        do
            path="/lib/modules/${ver}/updates/dkms/${mod}.${ext}"
            test -f "$path" && echo "$path"
        done
    done

    arch=$(echo "$arch" | tr -d ' :')
    echo "/var/lib/dkms/virtualbox/kernel-${ver}-${arch}"
done
echo /var/lib/dkms/virtualbox
